List<String> customerList = [
  'N.T.Son',
  'N.T.N.Ha',
  'N.M.Duc',
  'Elon Musk',
  'Jeff Bezos',
  'Bill Gates',
  'Mark Zuckerberg',
  'Barack Obama',
  'Narendra Modi',
  'Angela Merkel',
  'Xi Jinping',
  'Joe Biden',
  'Cristiano Ronaldo',
  'Lionel Messi',
  'Oprah Winfrey',
  'Beyoncé',
  'Taylor Swift',
  'Kim Kardashian',
  'Kanye West',
  'Rihanna',
  'LeBron James',
  'Stephen Curry',
  'Serena Williams',
  'Virat Kohli',
  'Novak Djokovic',
  'Emma Watson',
  'Dwayne "The Rock" Johnson',
  'Tom Hanks',
  'Ellen DeGeneres',
  'Adele',
  'Son H.M',
  'P.N.Vuong'
];
